
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - av.mittwald.de
  resources:
  - scheduledvirusscans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - av.mittwald.de
  resources:
  - scheduledvirusscans/finalizers
  verbs:
  - update
- apiGroups:
  - av.mittwald.de
  resources:
  - scheduledvirusscans/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - av.mittwald.de
  resources:
  - virusscans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - av.mittwald.de
  resources:
  - virusscans/finalizers
  verbs:
  - update
- apiGroups:
  - av.mittwald.de
  resources:
  - virusscans/status
  verbs:
  - get
  - patch
  - update
