# permissions for end users to view scheduledvirusscans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduledvirusscan-viewer-role
rules:
- apiGroups:
  - av.mittwald.de
  resources:
  - scheduledvirusscans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - av.mittwald.de
  resources:
  - scheduledvirusscans/status
  verbs:
  - get
