# permissions for end users to edit virusscans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virusscan-editor-role
rules:
- apiGroups:
  - av.mittwald.de
  resources:
  - virusscans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - av.mittwald.de
  resources:
  - virusscans/status
  verbs:
  - get
