# permissions for end users to view virusscans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virusscan-viewer-role
rules:
- apiGroups:
  - av.mittwald.de
  resources:
  - virusscans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - av.mittwald.de
  resources:
  - virusscans/status
  verbs:
  - get
