apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeav:operator
  labels: {{ include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - patch
    - update
    - list
    - get
    - watch
- apiGroups: [""]
  resources: [pods]
  verbs: [list, get, watch]
- apiGroups: [""]
  resources: [configmaps]
  verbs: ['*']
- apiGroups: ['batch']
  resources: ['jobs']
  verbs: ['*']
- apiGroups: ["apps"]
  resources: [daemonsets]
  verbs: [list, watch, get]
- apiGroups: ['av.mittwald.systems']
  resources:
    - virusscans
    - scheduledvirusscans
  verbs:
    - get
    - list
    - watch
- apiGroups: ['av.mittwald.systems']
  resources:
    - virusscans
  verbs:
    - create
    - delete
- apiGroups: ['av.mittwald.systems']
  resources:
    - virusscans/status
    - scheduledvirusscans/status
  verbs:
    - patch
    - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeav:operator:internal
  labels: {{ include "chart.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: [pods]
  verbs: [list, get, watch]
- apiGroups: [""]
  resources: [configmaps]
  verbs: ['*']
- apiGroups: ["apps"]
  resources: [daemonsets]
  verbs: ['*']