apiVersion: av.mittwald.de/v1beta1
kind: VirusScan
metadata:
  name: example-virusscan
spec:
  engine: ClamAV
  targets:
    - volume:
        persistentVolumeClaim:
          claimName: my-pvc
      subPath: path/to/subdir