// +build !ignore_autogenerated

/*
Copyright 2021 Mittwald CM Service GmbH & Co. KG.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledVirusScan) DeepCopyInto(out *ScheduledVirusScan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledVirusScan.
func (in *ScheduledVirusScan) DeepCopy() *ScheduledVirusScan {
	if in == nil {
		return nil
	}
	out := new(ScheduledVirusScan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScheduledVirusScan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledVirusScanList) DeepCopyInto(out *ScheduledVirusScanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScheduledVirusScan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledVirusScanList.
func (in *ScheduledVirusScanList) DeepCopy() *ScheduledVirusScanList {
	if in == nil {
		return nil
	}
	out := new(ScheduledVirusScanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScheduledVirusScanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledVirusScanSpec) DeepCopyInto(out *ScheduledVirusScanSpec) {
	*out = *in
	if in.HistorySize != nil {
		in, out := &in.HistorySize, &out.HistorySize
		*out = new(int)
		**out = **in
	}
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledVirusScanSpec.
func (in *ScheduledVirusScanSpec) DeepCopy() *ScheduledVirusScanSpec {
	if in == nil {
		return nil
	}
	out := new(ScheduledVirusScanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledVirusScanStatus) DeepCopyInto(out *ScheduledVirusScanStatus) {
	*out = *in
	if in.LastScheduledScan != nil {
		in, out := &in.LastScheduledScan, &out.LastScheduledScan
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.LastScheduledTime != nil {
		in, out := &in.LastScheduledTime, &out.LastScheduledTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledVirusScanStatus.
func (in *ScheduledVirusScanStatus) DeepCopy() *ScheduledVirusScanStatus {
	if in == nil {
		return nil
	}
	out := new(ScheduledVirusScanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirusScan) DeepCopyInto(out *VirusScan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirusScan.
func (in *VirusScan) DeepCopy() *VirusScan {
	if in == nil {
		return nil
	}
	out := new(VirusScan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirusScan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirusScanCondition) DeepCopyInto(out *VirusScanCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirusScanCondition.
func (in *VirusScanCondition) DeepCopy() *VirusScanCondition {
	if in == nil {
		return nil
	}
	out := new(VirusScanCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirusScanList) DeepCopyInto(out *VirusScanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirusScan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirusScanList.
func (in *VirusScanList) DeepCopy() *VirusScanList {
	if in == nil {
		return nil
	}
	out := new(VirusScanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirusScanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirusScanResultItem) DeepCopyInto(out *VirusScanResultItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirusScanResultItem.
func (in *VirusScanResultItem) DeepCopy() *VirusScanResultItem {
	if in == nil {
		return nil
	}
	out := new(VirusScanResultItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirusScanSpec) DeepCopyInto(out *VirusScanSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]VirusScanTargetSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirusScanSpec.
func (in *VirusScanSpec) DeepCopy() *VirusScanSpec {
	if in == nil {
		return nil
	}
	out := new(VirusScanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirusScanStatus) DeepCopyInto(out *VirusScanStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(map[VirusScanConditionType]VirusScanCondition, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Job != nil {
		in, out := &in.Job, &out.Job
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.ScanResults != nil {
		in, out := &in.ScanResults, &out.ScanResults
		*out = make([]VirusScanResultItem, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirusScanStatus.
func (in *VirusScanStatus) DeepCopy() *VirusScanStatus {
	if in == nil {
		return nil
	}
	out := new(VirusScanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirusScanTargetSpec) DeepCopyInto(out *VirusScanTargetSpec) {
	*out = *in
	in.Volume.DeepCopyInto(&out.Volume)
	if in.ExcludeFiles != nil {
		in, out := &in.ExcludeFiles, &out.ExcludeFiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeDirectories != nil {
		in, out := &in.ExcludeDirectories, &out.ExcludeDirectories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirusScanTargetSpec.
func (in *VirusScanTargetSpec) DeepCopy() *VirusScanTargetSpec {
	if in == nil {
		return nil
	}
	out := new(VirusScanTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirusScanTemplate) DeepCopyInto(out *VirusScanTemplate) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirusScanTemplate.
func (in *VirusScanTemplate) DeepCopy() *VirusScanTemplate {
	if in == nil {
		return nil
	}
	out := new(VirusScanTemplate)
	in.DeepCopyInto(out)
	return out
}
