name: Build & Test

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:

env:
  KUBECONFIG: /tmp/kubeconfig
  IMAGE_NAME: quay.io/mittwald/kubeav
  REGISTRY_URL: quay.io/mittwald

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install golangci-lint
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.28.3

      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run -v --timeout 30m

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

#      - name: Hack Code Climate and Go Modules
#        if: github.event_name != 'pull_request'
#        run: mkdir -p github.com/mittwald && ln -sf $(pwd) github.com/mittwald/harbor-operator
#
#      - name: Test & publish code coverage
#        if: github.event_name != 'pull_request'
#        uses: paambaati/codeclimate-action@v2.6.0
#        env:
#          CC_TEST_REPORTER_ID: ${{ secrets.codeClimateReporterID }}
#        with:
#          coverageCommand: go test -coverprofile=c.out ./...
#          debug: true
#          prefix: 'github.com/${{ github.repository }}/'

      - name: Go Test
        run: make test

  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --snapshot --skip-publish --rm-dist -f build/ci/.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_USER_TOKEN }}
