name: Create release

on:
  push:
    tags:
      - '*'

jobs:
  deploytagged:
    name: Deploy Tagged Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Registry Login
        run: docker login -u "${{ secrets.QUAY_IO_USER }}" -p "${{ secrets.QUAY_IO_TOKEN }}" quay.io

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Docker login
        run: docker login -u "${{ secrets.QUAY_IO_USER }}" -p "${{ secrets.QUAY_IO_TOKEN }}" quay.io

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist -f build/ci/.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_USER_TOKEN }}

      - name: Run chart version bump
        uses: mittwald/bump-app-version-action@v1
        with:
          mode: 'publish'
          chartYaml: './deploy/helm-chart/kubeav/Chart.yaml'
        env:
          GITHUB_TOKEN: "${{ secrets.RELEASE_USER_TOKEN }}"
          HELM_REPO_PASSWORD: "${{ secrets.HELM_REPO_PASSWORD }}"